// Lista de marcas conocidas
export const knownBrands = [
  "WHIRLPOOL",
  "SAMSUNG",
  "LG",
  "SONY",
  "PANASONIC",
  "PHILIPS",
  "BOSCH",
  "ELECTROLUX",
  "MABE",
  "GENERAL ELECTRIC",
  "PEABODY",
  "ATMA",
  "SMART-TEK",
  "KANJI",
  "MIDEA",
  "OVERTECH",
  "TELEFUNKEN",
  "HITACHI",
  "NOBLEX",
  "BLAUPUNKT",
  "DREAN",
  "INOX",
  "STANDBY",
  "ARISTON",
  "VONDOM",
  "NOGA",
  "JBL",
  "PHILCO",
  "STROMBERG",
  "XIAOMI",
  "DIAMONDX",
  "SUONO",
  "HARMAN KARDON",
  "CROWN MUSTANG",
  "HISENSE",
  "TCL",
  "AOC",
  "ENOVA",
  "FHD",
  "BGH",
];

export const BASE_URLS = {
  naldo: "https://www.naldo.com.ar",
  cetrogar: "https://www.cetrogar.com.ar",
  musimundo: "https://u.braindw.com",
  fravega: "https://www.fravega.com",
  carrefour: "https://www.carrefour.com.ar",
};

export const STORES_MAP = {
  naldo: "Naldo",
  cetrogar: "Cetrogar",
  musimundo: "Musimundo",
  fravega: "Frávega",
  carrefour: "Carrefour",
};

export const STORES = [
  STORES_MAP.naldo,
  STORES_MAP.cetrogar,
  STORES_MAP.musimundo,
  STORES_MAP.fravega,
  STORES_MAP.carrefour,
];
