// Lista de marcas conocidas
export const knownBrands = [
  "WHIRLPOOL",
  "SAMSUNG",
  "LG",
  "SONY",
  "PANASONIC",
  "PHILIPS",
  "BOSCH",
  "ELECTROLUX",
  "MABE",
  "GENERAL ELECTRIC",
  "PEABODY",
  "ATMA",
  "SMART-TEK",
  "SMART TEK",
  "KANJI",
  "MIDEA",
  "OVERTECH",
  "TELEFUNKEN",
  "HITACHI",
  "NOBLEX",
  "BLAUPUNKT",
  "DREAN",
  "INOX",
  "STANDBY",
  "ARISTON",
  "VONDOM",
  "NOGA",
  "JBL",
  "PHILCO",
  "STROMBERG",
  "XIAOMI",
  "DIAMONDX",
  "SUONO",
  "HARMAN KARDON",
  "CROWN MUSTANG",
  "HISENSE",
  "TCL",
  "AOC",
  "ENOVA",
  "FHD",
  "BGH",
  "ULTRACOMB",
  "DAEWOO",
  "EIFFEL",
  "WHITENBLACK",
  "GOLDSTAR",
  "BLACK&DECKER",
  "BLACK+DECKER",
  "GADNIC",
  "MOULINEX",
  "LILIANA",
  "SMARTLIFE",
  "OSTER",
  "BYNOX",
  "VONNE",
  "PIONEER",
  "X-VIEW",
];

export const ALL = "TODAS";

export const BASE_URLS = {
  naldo: "https://www.naldo.com.ar",
  cetrogar: "https://www.cetrogar.com.ar",
  musimundo: "https://u.braindw.com",
  fravega: "https://www.fravega.com",
  carrefour: "https://www.carrefour.com.ar",
};

export const STORES_MAP = {
  naldo: "Naldo",
  cetrogar: "Cetrogar",
  musimundo: "Musimundo",
  fravega: "Frávega",
  carrefour: "Carrefour",
  megatone: "Megatone",
  masOnline: "Mas Online",
  rex: "Rex",
  mercadoLibre: "Mercado Libre",
};

export const STORES = [
  STORES_MAP.naldo,
  STORES_MAP.cetrogar,
  STORES_MAP.musimundo,
  STORES_MAP.fravega,
  STORES_MAP.carrefour,
];
